apiVersion: app/v1
kind: Deployment
metadata: 
  name: house-backend
spec:
  replicas: 2
  selector:
    matchlabels:
      app: house-backend
  template: 
    metadata:
      labels:
        app: house-backend
    spec:
      containers:
        - name: house-backend
          image: sudhir9999/house-backend:latest
          ports: 
            - containers    