apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-backend
  template:
    metadata:
      labels:
        app: house-backend
    spec:
      containers:
        - name: house-backend
          image: sudhir9999/house-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/house
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root