apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-frontend
  template:
    metadata:
      labels:
        app: house-frontend
    spec:
      containers:
        - name: house-frontend
          image: sudhir9999/house-frontend:latest
          ports:
            - containerPort: 80